#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting RPI Watchdog Service"
    systemctl enable waggle-rpi-watchdog.service
    systemctl start waggle-rpi-watchdog.service || true
    ;;
esac
